-- Misconception Hunter: session persistence for shareable report permalinks.
--
-- Deliberately one denormalized table rather than sessions/turns/reports
-- split into three: the only query pattern right now is "fetch one session
-- by its public id" (the /s/[id] permalink). Normalize when cross-session
-- analytics (Tier 5) actually needs it.
--
-- id is a short, random, unguessable string generated by the app
-- (see lib/db.ts) rather than an auto-incrementing int, so permalinks can't
-- be enumerated by walking sequential ids.

create table if not exists public.sessions (
  id text primary key,
  created_at timestamptz not null default now(),
  topic text,
  transcript jsonb not null,
  summary jsonb not null
);

-- All reads/writes go through server-side API routes using the service role
-- key, which bypasses RLS entirely -- so RLS is enabled with no policies,
-- which denies all access via the public anon key. This table is never
-- queried directly from the browser.
alter table public.sessions enable row level security;

-- RLS bypass (service_role's BYPASSRLS attribute) only skips row-level
-- policies -- the role still needs the ordinary table-level grants below,
-- which aren't automatic for a table created directly via the SQL editor.
grant select, insert on public.sessions to service_role;
