import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { getSession } from '@/lib/db';
import { ReportBody } from '@/components/ReportBody';

type Props = { params: Promise<{ id: string }> };

const ASSESSMENT_SUMMARY: Record<string, string> = {
  concept_understood: 'The student demonstrated correct reasoning, not just a correct answer.',
  misconception_confirmed: 'A specific misconception was found and named.',
  insufficient_evidence: 'The conversation didn\'t produce enough evidence for a verdict either way.',
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const session = await getSession(id);

  if (!session) {
    return { title: 'Session not found — Misconception Hunter' };
  }

  const title = `${session.summary.topic || 'Session report'} — Misconception Hunter`;
  const description =
    ASSESSMENT_SUMMARY[session.summary.overallAssessment] ??
    'A Socratic misconception-hunting session report.';

  return {
    title,
    description,
    openGraph: { title, description, type: 'article' },
    twitter: { card: 'summary', title, description },
  };
}

export default async function SharedSessionPage({ params }: Props) {
  const { id } = await params;
  const session = await getSession(id);

  if (!session) {
    notFound();
  }

  const createdAt = new Date(session.created_at).toLocaleString(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  });

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="flex items-center justify-between border-b border-border px-4 py-4 md:px-6">
        <Link href="/" className="flex items-center gap-2">
          <Image
            src="/agora-logo-mark.svg"
            alt=""
            width={28}
            height={28}
            className="h-7 w-7 object-contain"
          />
          <span className="text-sm font-semibold tracking-[-0.025em]">Misconception Hunter</span>
        </Link>
        <Link
          href="/"
          className="rounded-md border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground transition-colors hover:border-primary hover:text-foreground"
        >
          Try it yourself
        </Link>
      </header>

      <main className="mx-auto flex max-w-2xl flex-col gap-6 px-4 py-10">
        <div>
          <h1 className="text-xl font-semibold text-foreground">Session Report</h1>
          <p className="mt-1 text-sm text-muted-foreground">{createdAt}</p>
        </div>

        <div className="rounded-[20px] border border-border bg-card/40 px-8 py-8 text-left shadow-[0_10px_24px_rgba(0,0,0,0.28)]">
          <ReportBody summary={session.summary} />
        </div>

        <details className="rounded-lg border border-border bg-card/20 px-4 py-3">
          <summary className="cursor-pointer text-sm font-medium text-foreground">
            Full transcript ({session.transcript.length} turns)
          </summary>
          <div className="mt-4 flex flex-col gap-3">
            {session.transcript.map((turn, index) => (
              <div key={index} className="text-sm">
                <span className="font-medium text-foreground">
                  {turn.role === 'user' ? 'Student: ' : 'Tutor: '}
                </span>
                <span className="text-muted-foreground">{turn.text}</span>
              </div>
            ))}
          </div>
        </details>

        <p className="text-xs text-muted-foreground">
          This report was generated by an LLM reading the session transcript — a best-effort
          structured summary, not a verified pedagogical assessment.
        </p>
      </main>
    </div>
  );
}
